# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32d22947077193b2507ab2843ddc0ca614060c6bf38ea1c7549adbd2788d520b9874a90e277d0f8a50102433cd58a3c8a1f09ab924534805943bfb68579fc83

test:
  secret_key_base: e2d78fd836d854d8d81a9326890f328825ea56ff9501fc8008bec5ca17da949de616cbbb010c2cf4d36b5806fd3db8f578723c6e209ce167cb7d9ab36b7f3114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
